---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronstabledemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronstabledemo
  template:
    metadata:
      labels:
        app: cronstabledemo
    spec:
      containers:
      - name: cronstabledemo
        image: cronstabledemo
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        env:
          - name: PYTHONIOENCODING
            value: "utf-8"
