---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yacron2demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yacron2demo
    spec:
      containers:
      - name: yacron2demo
        image: yacron2demo
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        env:
          - name: PYTHONIOENCODING
            value: "utf-8"
