"""In-house cron expression engine.

:class:`CronTab` parses the crontab dialect yacron2 has always accepted and
answers the two questions the scheduler asks: "when does this fire next?"
(:meth:`CronTab.next`) and "does this instant match?" (:meth:`CronTab.test`).

It replaces the third-party ``crontab`` (parse-crontab) dependency yacron2
previously leaned on, moving the one piece of syntax every job depends on
into the tree.  Compatibility with that library is not aspirational -- it is
enforced by golden vectors recorded from it across 180+ expressions and
fixed instants (DST transitions, leap days, month/year boundaries, the year
cap, microsecond nows, ambiguous-time folds): see
``tests/data/cron_golden.json``, regenerated by
``tests/gen_cron_golden.py`` and replayed by ``tests/test_cronexpr.py``.

The dialect (unchanged; the "Schedules and Timezones" wiki page is the user
documentation):

- 5 fields ``minute hour dayOfMonth month dayOfWeek`` (implicit second ``0``,
  any year); 6 fields add a trailing ``year`` column; 7 fields add a leading
  ``second`` column too.
- Per field: values, lists (``1,15,30``), ranges (``1-5``), steps (``*/5``,
  ``1-9/2``, and ``5/15`` -- a bare start with a step runs to the field's
  end), month and weekday names (``jan``, ``mon-fri``), case-insensitive.
- Weekdays are ``0``-``7`` with BOTH 0 and 7 meaning Sunday; a range ending
  in 0 wraps its end to 7 (so ``sat-sun`` and ``6-0`` work); star/step
  expansion runs 0-6.
- ``L`` alone in day-of-month is the month's last day; ``L<n>`` (or
  ``L<a>-<b>``) in day-of-week is the month's LAST such weekday (``L5`` =
  last Friday).  No other field takes an ``L``.
- ``@yearly``/``@annually``/``@monthly``/``@weekly``/``@daily``/``@hourly``
  expand to their classic five-field forms.  ``@reboot`` never reaches this
  parser (the scheduler gives it meaning) and ``@midnight`` is rewritten to
  ``@daily`` by the classic-crontab loader, exactly as before.
- When day-of-month AND day-of-week are both restricted, a day must satisfy
  BOTH (``0 0 13 * 5`` = Friday the 13th).  This is parse-crontab's rule,
  deliberately preserved (Vixie cron fires on either) so that no existing
  schedule changes meaning.
- The ``year`` column accepts 1970-2099.  :meth:`test` does not bound the
  year when the column is ``*`` or absent, but :meth:`next` never searches
  past 2099 and returns ``None`` for a schedule with no remaining occurrence
  (``0 0 30 2 * *``, or a fixed past year) -- callers drop such jobs from
  the fire index.

Time model (also preserved): :meth:`next` is strictly future -- an instant
that matches "now" yields the following occurrence, so index seeding stays
strictly-future.  The search runs in the CIVIL clock of the ``now`` it is
given: for an aware ``now`` the matching wall-clock instant is resolved back
in ``now``'s own zone (``fold=0``) and the returned delay is the true elapsed
seconds across any UTC-offset change.  Concretely, on a spring-forward day a
``0 3 * * *`` job one civil minute after 01:59 fires in 60 real seconds, and
an ambiguous fall-back wall time fires on its first occurrence only.
:meth:`test` reads the civil fields of the datetime it is handed (aware or
naive) and ignores microseconds.
"""

import calendar
import datetime
from typing import FrozenSet, Iterator, Mapping, Optional, Set, Tuple

__all__ = ["CronTab"]

_MACROS = {
    "@yearly": "0 0 1 1 *",
    "@annually": "0 0 1 1 *",
    "@monthly": "0 0 1 * *",
    "@weekly": "0 0 * * 0",
    "@daily": "0 0 * * *",
    "@hourly": "0 * * * *",
}

_MONTH_NAMES = {
    "jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6,
    "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12,
}

_DOW_NAMES = {
    "sun": 0, "mon": 1, "tue": 2, "wed": 3,
    "thu": 4, "fri": 5, "sat": 6,
}

#: next() never searches past this year: the year column's own maximum, and
#: the horizon that makes a never-occurring schedule (Feb 30) come back as
#: ``None`` instead of looping forever.
_YEAR_HORIZON = 2099

# (label, lo, hi, step_end, names): ``hi`` bounds explicit values, while
# ``step_end`` is the implicit end of star/bare-start expansions.  They only
# differ for the weekday field, where an explicit 7 is legal (Sunday again)
# but ``*`` and ``5/2`` expand over 0-6.
_SECOND = ("second", 0, 59, 59, None)
_MINUTE = ("minute", 0, 59, 59, None)
_HOUR = ("hour", 0, 23, 23, None)
_DOM = ("day-of-month", 1, 31, 31, None)
_MONTH = ("month", 1, 12, 12, _MONTH_NAMES)
_DOW = ("day-of-week", 0, 7, 6, _DOW_NAMES)
_YEAR = ("year", 1970, _YEAR_HORIZON, _YEAR_HORIZON, None)

_FieldSpec = Tuple[str, int, int, int, Optional[Mapping[str, int]]]


def _resolve(token: str, spec: _FieldSpec, item: str) -> int:
    """One value token -> int, via the field's name table or base 10."""
    label, lo, hi, _end, names = spec
    if names is not None and token in names:
        value = names[token]
    else:
        try:
            value = int(token, 10)
        except ValueError:
            raise ValueError(
                "invalid {} field {!r}".format(label, item)
            ) from None
    if not lo <= value <= hi:
        raise ValueError(
            "{} value {} out of range [{}, {}]".format(label, value, lo, hi)
        )
    return value


def _parse_item(item: str, spec: _FieldSpec) -> Iterator[int]:
    """Expand one comma-separated item (``*``, ``a``, ``a-b``, with ``/n``).

    Mirrors the old library's validation exactly: a step must be positive,
    no larger than the field's ``hi``, and ``start + step`` must land back
    inside the field's range (so ``*/12`` in the 1-12 month field or
    ``50-59/15`` in the minute field are rejected); a reversed range is an
    error, except that a day-of-week range ending in 0 wraps to 7.
    """
    label, lo, hi, step_end, _names = spec
    head, slash, step_text = item.partition("/")
    step = 1
    if slash:
        if "/" in step_text:
            raise ValueError(
                "invalid {} field {!r}: more than one '/'".format(label, item)
            )
        try:
            step = int(step_text, 10)
        except ValueError:
            raise ValueError(
                "invalid {} step {!r}".format(label, item)
            ) from None
        if step <= 0:
            raise ValueError(
                "{} step must be positive, got {}".format(label, step)
            )
        if step > hi:
            raise ValueError(
                "{} step {} too large (max {})".format(label, step, hi)
            )
    if head == "*":
        start, end = lo, step_end
    elif "-" in head:
        a, _, b = head.partition("-")
        start = _resolve(a, spec, item)
        end = _resolve(b, spec, item)
        if end == 0 and spec is _DOW:
            # A day-of-week range ending in 0 reads its end as Sunday-as-7,
            # UNCONDITIONALLY: 6-0/sat-sun is Sat+Sun, and the degenerate
            # 0-0/sun-sun becomes 0-7, every day (a preserved quirk).
            end = 7
        if start > end:
            raise ValueError(
                "{} range start {} > end {}".format(label, start, end)
            )
    else:
        start = _resolve(head, spec, item)
        if not slash:
            yield start
            return
        end = step_end
        if start > end:
            raise ValueError(
                "{} range start {} > end {}".format(label, start, end)
            )
    if slash and not lo <= start + step <= hi:
        raise ValueError(
            "{} step {} from {} escapes [{}, {}]".format(
                label, step, start, lo, hi
            )
        )
    yield from range(start, end + 1, step)


def _parse_plain(text: str, spec: _FieldSpec) -> FrozenSet[int]:
    """A field with no ``L`` forms (second/minute/hour/month/year)."""
    values: Set[int] = set()
    for item in text.split(","):
        if item.startswith("l"):
            raise ValueError(
                "'L' is only valid in the day-of-month and day-of-week "
                "fields, not {}".format(spec[0])
            )
        values.update(_parse_item(item, spec))
    return frozenset(values)


def _parse_dom(text: str) -> Tuple[FrozenSet[int], bool]:
    """Day-of-month: plain values plus an optional bare ``L`` (last day)."""
    values: Set[int] = set()
    last = False
    for item in text.split(","):
        if item == "l":
            last = True
        elif item.startswith("l"):
            raise ValueError(
                "'L' in the day-of-month field must stand alone "
                "(got {!r})".format(item)
            )
        else:
            values.update(_parse_item(item, _DOM))
    return frozenset(values), last


def _parse_dow(text: str) -> Tuple[FrozenSet[int], FrozenSet[int]]:
    """Day-of-week: plain values plus ``L``-prefixed last-weekday items.

    Both sets are normalized so 7 (Sunday) is stored as 0; matching then
    never needs the 0/7 equivalence.
    """
    values: Set[int] = set()
    last: Set[int] = set()
    for item in text.split(","):
        if item == "l":
            raise ValueError(
                "a bare 'L' is only valid in the day-of-month field; in "
                "day-of-week write L<n> (e.g. L5 = last Friday)"
            )
        if item.startswith("l"):
            # L<n> or L<a>-<b>, strictly numeric (no names, steps or `*`),
            # each value 0..7.  Unlike a plain range, a reversed L-range is
            # NOT an error -- it is legal and matches nothing -- and an end
            # of 0 stays 0 (no Sunday-as-7 wrap).  Preserved quirks.
            a, dash, b = item[1:].partition("-")
            if not a.isdigit() or (dash and not b.isdigit()):
                raise ValueError(
                    "an L day-of-week item takes a day number or numeric "
                    "range 0..7, got {!r}".format(item)
                )
            lo = int(a, 10)
            hi = int(b, 10) if dash else lo
            for value in (lo, hi):
                if not 0 <= value <= 7:
                    raise ValueError(
                        "day-of-week value {} out of range [0, 7]".format(
                            value
                        )
                    )
            last.update(range(lo, hi + 1))
        else:
            values.update(_parse_item(item, _DOW))
    return (
        frozenset(v % 7 for v in values),
        frozenset(v % 7 for v in last),
    )


class CronTab:
    """One parsed cron expression; see the module docstring for the dialect.

    Equality is semantic -- two expressions that fire on the identical set
    of instants compare equal (``*/5 * * * *`` == ``0-59/5 * * * *``,
    ``@daily`` == ``0 0 * * *``) -- because the scheduler's reload path uses
    ``==`` to keep an unchanged job's next-fire instant (see
    ``Cron._same_schedule``).  Instances are deliberately unhashable, like
    the class this replaced.  ``str()`` is the whitespace-normalized source
    expression, giving the dag scheduler's schedule signature a stable value
    across reloads.
    """

    __slots__ = (
        "_source",
        "_seconds",
        "_minutes",
        "_hours",
        "_dom",
        "_dom_last",
        "_months",
        "_dow",
        "_dow_last",
        "_years",
        "_hours_sorted",
        "_minutes_sorted",
        "_seconds_sorted",
        "_months_sorted",
        "_years_sorted",
    )

    def __init__(self, crontab: str) -> None:
        self._source = " ".join(crontab.split())
        fields = crontab.lower().split()
        if len(fields) == 1 and fields[0] in _MACROS:
            self._source = fields[0]
            fields = _MACROS[fields[0]].split()
        if not 5 <= len(fields) <= 7:
            raise ValueError(
                "expected 5 to 7 whitespace-separated cron fields "
                "(or a supported @-nickname), got {}".format(len(fields))
            )
        # 5 fields: implicit second 0, any year.  6 fields: a trailing year
        # column.  7 fields: a leading second column as well.
        if len(fields) == 7:
            second_text = fields[0]
            fields = fields[1:]
        else:
            second_text = "0"
        if len(fields) == 6:
            year_text: Optional[str] = fields[5]
            if year_text == "*":
                year_text = None  # matches like an absent column
        else:
            year_text = None
        self._seconds = _parse_plain(second_text, _SECOND)
        self._minutes = _parse_plain(fields[0], _MINUTE)
        self._hours = _parse_plain(fields[1], _HOUR)
        self._dom, self._dom_last = _parse_dom(fields[2])
        self._months = _parse_plain(fields[3], _MONTH)
        self._dow, self._dow_last = _parse_dow(fields[4])
        self._years: Optional[FrozenSet[int]] = (
            _parse_plain(year_text, _YEAR) if year_text is not None else None
        )
        self._seconds_sorted = tuple(sorted(self._seconds))
        self._minutes_sorted = tuple(sorted(self._minutes))
        self._hours_sorted = tuple(sorted(self._hours))
        self._months_sorted = tuple(sorted(self._months))
        self._years_sorted = (
            tuple(sorted(self._years)) if self._years is not None else None
        )

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------
    def __str__(self) -> str:
        return self._source

    def __repr__(self) -> str:
        return "CronTab({!r})".format(self._source)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, CronTab):
            return False
        return (
            self._seconds == other._seconds
            and self._minutes == other._minutes
            and self._hours == other._hours
            and self._dom == other._dom
            and self._dom_last == other._dom_last
            and self._months == other._months
            and self._dow == other._dow
            and self._dow_last == other._dow_last
            and self._years == other._years
        )

    # __eq__ without __hash__ makes instances unhashable, matching the old
    # class; nothing in yacron2 keys on a CronTab.

    # ------------------------------------------------------------------
    # Matching
    # ------------------------------------------------------------------
    def test(self, entry: datetime.datetime) -> bool:
        """Whether ``entry``'s civil fields match (microseconds ignored)."""
        return (
            entry.second in self._seconds
            and entry.minute in self._minutes
            and entry.hour in self._hours
            and entry.month in self._months
            and (self._years is None or entry.year in self._years)
            and self._day_matches(entry.year, entry.month, entry.day)
        )

    def _day_matches(self, year: int, month: int, day: int) -> bool:
        """The AND of the day-of-month and day-of-week constraints."""
        month_end = calendar.monthrange(year, month)[1]
        if day not in self._dom and not (
            self._dom_last and day == month_end
        ):
            return False
        # Python weekday(): Mon=0..Sun=6 -> cron: Sun=0..Sat=6.
        dow = (datetime.date(year, month, day).weekday() + 1) % 7
        if dow in self._dow:
            return True
        return (
            dow in self._dow_last
            and day > month_end - 7  # the month's last such weekday
        )

    # ------------------------------------------------------------------
    # Next occurrence
    # ------------------------------------------------------------------
    def next(
        self,
        now: Optional[datetime.datetime] = None,
        default_utc: bool = False,
    ) -> Optional[float]:
        """Seconds until the next occurrence STRICTLY after ``now``.

        ``None`` when the schedule never occurs again (a fixed past year, or
        a date that never exists) -- the search stops at year 2099.  For an
        aware ``now`` the result is true elapsed seconds: the matching civil
        instant is resolved in ``now``'s zone (``fold=0``), so a DST change
        inside the interval is accounted for.  ``default_utc`` only matters
        when ``now`` is omitted: it picks the UTC instead of the local wall
        clock, exactly like the library this replaced.
        """
        if now is None:
            if default_utc:
                now = datetime.datetime.now(
                    datetime.timezone.utc
                ).replace(tzinfo=None)
            else:
                now = datetime.datetime.now()
        civil = now.replace(tzinfo=None)
        target = self._next_civil(civil)
        if target is None:
            return None
        if now.tzinfo is not None:
            # Subtracting two datetimes that share a tzinfo is NAIVE (civil)
            # arithmetic in Python; route through UTC so the delay is true
            # elapsed seconds across a DST offset change.
            target_utc = target.replace(tzinfo=now.tzinfo).astimezone(
                datetime.timezone.utc
            )
            return (target_utc - now).total_seconds()
        return (target - civil).total_seconds()

    def _next_civil(
        self, civil: datetime.datetime
    ) -> Optional[datetime.datetime]:
        """Smallest whole-second civil instant strictly after ``civil``."""
        base = civil.replace(microsecond=0) + datetime.timedelta(seconds=1)
        year, month, day = base.year, base.month, base.day
        tod: Optional[datetime.time] = base.time()
        while year <= _YEAR_HORIZON:
            years_sorted = self._years_sorted
            if years_sorted is not None and year not in years_sorted:
                next_year = self._next_in(years_sorted, year)
                if next_year is None:
                    return None
                year, month, day, tod = next_year, 1, 1, None
                continue
            if month not in self._months:
                nxt = self._next_in(self._months_sorted, month)
                if nxt is None:
                    year, month = year + 1, self._months_sorted[0]
                else:
                    month = nxt
                day, tod = 1, None
                continue
            month_end = calendar.monthrange(year, month)[1]
            while day <= month_end:
                if self._day_matches(year, month, day):
                    t = self._first_time(tod)
                    if t is not None:
                        return datetime.datetime.combine(
                            datetime.date(year, month, day), t
                        )
                day += 1
                tod = None
            month += 1
            day, tod = 1, None
            if month > 12:
                year, month = year + 1, 1
        return None

    @staticmethod
    def _next_in(ordered: Tuple[int, ...], current: int) -> Optional[int]:
        """First element of ``ordered`` greater than ``current``."""
        for value in ordered:
            if value > current:
                return value
        return None

    def _first_time(
        self, at_or_after: Optional[datetime.time]
    ) -> Optional[datetime.time]:
        """Earliest matching time of day, at/after ``at_or_after`` if set."""
        if at_or_after is None:
            return datetime.time(
                self._hours_sorted[0],
                self._minutes_sorted[0],
                self._seconds_sorted[0],
            )
        for hour in self._hours_sorted:
            if hour < at_or_after.hour:
                continue
            if hour > at_or_after.hour:
                return datetime.time(
                    hour, self._minutes_sorted[0], self._seconds_sorted[0]
                )
            for minute in self._minutes_sorted:
                if minute < at_or_after.minute:
                    continue
                if minute > at_or_after.minute:
                    return datetime.time(
                        hour, minute, self._seconds_sorted[0]
                    )
                for second in self._seconds_sorted:
                    if second >= at_or_after.second:
                        return datetime.time(hour, minute, second)
        return None
