FROM alpine:3.24

RUN apk add \
		curl git ca-certificates alpine-sdk bash \
		openssl-dev readline-dev zlib-dev libffi-dev

RUN curl https://pyenv.run | bash

ENV PATH="/root/.pyenv/bin:$PATH"

RUN pyenv install -l | grep 3.13
RUN CONFIGURE_OPTS=--enable-shared pyenv install 3.13.5
RUN pyenv global 3.13.5

RUN /root/.pyenv/versions/3.13.5/bin/python -m venv /yacron2
ENV PATH=/yacron2/bin:$PATH
RUN pip install -U pip setuptools pyinstaller==6.21.0

COPY . /root/yacron2
WORKDIR /root/yacron2
RUN git status
RUN python setup.py install
RUN python pyinstaller/yacron2 --version
RUN pyinstaller pyinstaller/yacron2.spec
RUN ls -sFh dist/yacron2
RUN dist/yacron2 --version
