"""In-house cron expression engine.

:class:`CronTab` parses the crontab dialect cronstable has always accepted and
answers the two questions the scheduler asks: "when does this fire next?"
(:meth:`CronTab.next`) and "does this instant match?" (:meth:`CronTab.test`).
The tooling around the scheduler gets three more: :meth:`CronTab.prev` (the
most recent past occurrence), :meth:`CronTab.occurrences` (iterate the exact
instants the scheduler would fire) and read-only properties exposing the
parsed field sets, so linters and describers work from ground truth instead
of re-parsing the text.

It replaces the third-party ``crontab`` (parse-crontab) dependency cronstable
previously leaned on, moving the one piece of syntax every job depends on
into the tree.  Compatibility with that library is not aspirational -- it is
enforced by golden vectors recorded from it across 180+ expressions and
fixed instants (DST transitions, leap days, month/year boundaries, the year
cap, microsecond nows, ambiguous-time folds): see
``tests/data/cron_golden.json``, regenerated by
``tests/gen_cron_golden.py`` and replayed by ``tests/test_cronexpr.py``.

The dialect (unchanged; the "Schedules and Timezones" wiki page is the user
documentation):

- 5 fields ``minute hour dayOfMonth month dayOfWeek`` (implicit second ``0``,
  any year); 6 fields add a trailing ``year`` column; 7 fields add a leading
  ``second`` column too.
- Per field: values, lists (``1,15,30``), ranges (``1-5``), steps (``*/5``,
  ``1-9/2``, and ``5/15`` -- a bare start with a step runs to the field's
  end), month and weekday names (``jan``, ``mon-fri``), case-insensitive.
- Weekdays are ``0``-``7`` with BOTH 0 and 7 meaning Sunday; a range ending
  in 0 wraps its end to 7 (so ``sat-sun`` and ``6-0`` work); star/step
  expansion runs 0-6.
- ``L`` alone in day-of-month is the month's last day; ``L<n>`` (or
  ``L<a>-<b>``) in day-of-week is the month's LAST such weekday (``L5`` =
  last Friday).  No other field takes an ``L``.
- ``@yearly``/``@annually``/``@monthly``/``@weekly``/``@daily``/``@hourly``
  expand to their classic five-field forms.  ``@reboot`` never reaches this
  parser (the scheduler gives it meaning) and ``@midnight`` is rewritten to
  ``@daily`` by the classic-crontab loader, exactly as before.
- ``?`` standing alone in day-of-month or day-of-week reads as ``*``: the
  Quartz spelling of "unrestricted", accepted so a 7-field Quartz expression
  (whose column layout matches this dialect's) parses verbatim.  Anywhere
  else ``?`` stays an error, and parse errors whose text smells of Quartz
  (``#``, ``W``, the seconds-first 6-field layout) carry a hint naming that
  dialect instead of leaving the user to guess.
- ``H`` (Jenkins-style) in any field but the year: a value hashed from the
  job's name, stable across restarts, reloads and hosts, so a fleet of
  ``H * * * *`` jobs spreads across the hour instead of stampeding at :00
  while each job keeps ONE predictable slot (random jitter would break
  late-run detection; a hashed slot does not).  Forms: bare ``H`` (whole
  field range), ``H(a-b)`` (a numeric range), ``H/n`` and ``H(a-b)/n``
  (every ``n`` starting at a hashed offset); in day-of-month the rangeless
  forms (bare ``H`` and ``H/n``) hash over 1-28 so a short month is never
  silently skipped.  The seed is the
  ``hash_key`` handed to :class:`CronTab` (the job name everywhere
  cronstable constructs one), salted per field so ``H H * * *`` picks
  uncorrelated minute and hour; renaming a job re-hashes its slots.  A
  context that supplies no ``hash_key`` rejects ``H`` with a clear error.
  :attr:`CronTab.resolved_source` is the expression with every ``H``
  replaced by the values it hashed to.
- When day-of-month AND day-of-week are both restricted, a day must satisfy
  BOTH (``0 0 13 * 5`` = Friday the 13th).  This is parse-crontab's rule,
  deliberately preserved (Vixie cron fires on either) so that no existing
  schedule changes meaning.
- The ``year`` column accepts 1970-2099.  :meth:`test` does not bound the
  year when the column is ``*`` or absent, but :meth:`next` never searches
  past 2099 and returns ``None`` for a schedule with no remaining occurrence
  (``0 0 30 2 * *``, or a fixed past year) -- callers drop such jobs from
  the fire index.

Time model (also preserved): :meth:`next` is strictly future -- an instant
that matches "now" yields the following occurrence, so index seeding stays
strictly-future.  The search runs in the CIVIL clock of the ``now`` it is
given: for an aware ``now`` the matching wall-clock instant is resolved back
in ``now``'s own zone (``fold=0``) and the returned delay is the true elapsed
seconds across any UTC-offset change.  Concretely, on a spring-forward day a
``0 3 * * *`` job one civil minute after 01:59 fires in 60 real seconds, and
an ambiguous fall-back wall time fires on its first occurrence only.
:meth:`test` reads the civil fields of the datetime it is handed (aware or
naive) and ignores microseconds.

:meth:`prev` mirrors :meth:`next` into the past: seconds since the most
recent occurrence STRICTLY before ``now``, ``None`` when nothing occurs at or
after 1970 (the year column's floor).  :meth:`occurrences` iterates forward
and, for an aware start, steps through REAL instants the way the scheduler
does: a wall time a spring-forward transition skips is yielded once at its
shifted label, and a repeated fall-back wall time is yielded on its first
occurrence only, so consumers never see one real instant twice.
"""

import calendar
import datetime
import hashlib
import re
from typing import (
    FrozenSet,
    Iterator,
    List,
    Mapping,
    Optional,
    Set,
    Tuple,
)

__all__ = ["CronTab"]

_MACROS = {
    "@yearly": "0 0 1 1 *",
    "@annually": "0 0 1 1 *",
    "@monthly": "0 0 1 * *",
    "@weekly": "0 0 * * 0",
    "@daily": "0 0 * * *",
    "@hourly": "0 * * * *",
}

_MONTH_NAMES = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}

_DOW_NAMES = {
    "sun": 0,
    "mon": 1,
    "tue": 2,
    "wed": 3,
    "thu": 4,
    "fri": 5,
    "sat": 6,
}

#: next() never searches past this year: the year column's own maximum, and
#: the horizon that makes a never-occurring schedule (Feb 30) come back as
#: ``None`` instead of looping forever.
_YEAR_HORIZON = 2099

#: prev() never searches before this year: the year column's own minimum,
#: the backward mirror of ``_YEAR_HORIZON``.
_YEAR_FLOOR = 1970

#: a day-field item that is Quartz's nearest-weekday form (``15W``, ``LW``)
_QUARTZ_W = re.compile(r"(?:l|\d+)w\Z")

#: the accepted spellings of a hashed item: ``h``, ``h/n``, ``h(a-b)``,
#: ``h(a-b)/n`` (matched against the lowercased item).  Anything else that
#: opens with ``h`` is a malformed hash item, not a value (no month or
#: weekday name starts with an ``h``).
_HASH_ITEM = re.compile(r"h(?:\((\d+)-(\d+)\))?(?:/(\d+))?\Z")

#: a rangeless ``H`` form (bare ``H`` or ``H/n``) in day-of-month hashes
#: over this range, not 1-31: a hashed day of 29, 30 or 31 would silently
#: skip the months too short to reach it, which is exactly the surprise
#: ``H`` exists to avoid.  An explicit ``H(1-31)`` still opts in to the
#: full range.
_HASH_DOM_END = 28


def _quartz_hint(fields: Tuple[str, ...]) -> Optional[str]:
    """Extra text for a parse error that smells like Quartz syntax.

    Quartz cron differs from this dialect in the ways users actually trip
    over: ``#`` (nth weekday), ``W`` (nearest weekday), and a seconds-FIRST
    6-field layout where this dialect's 6th field is a trailing year.  When
    a failed expression carries one of those signatures, name the dialect
    and say what to do, instead of leaving a bare field error.
    """
    for field in fields:
        for item in field.split(","):
            if "#" in item:
                return (
                    "'#' is Quartz's nth-weekday form, which is not "
                    "supported; 'L<n>' selects the month's last such weekday"
                )
            if _QUARTZ_W.match(item):
                return (
                    "'W' is Quartz's nearest-weekday form, "
                    "which is not supported"
                )
    if "?" in fields:
        if len(fields) == 6:
            return (
                "this looks like a 6-field Quartz expression (seconds "
                "first); here the 6th field is a year, so append a "
                "trailing '*' to read it as second minute hour "
                "day-of-month month day-of-week year"
            )
        return (
            "'?' is only accepted standing alone in the day-of-month "
            "and day-of-week fields, where it reads as '*'"
        )
    return None


# (label, lo, hi, step_end, names): ``hi`` bounds explicit values, while
# ``step_end`` is the implicit end of star/bare-start expansions.  They only
# differ for the weekday field, where an explicit 7 is legal (Sunday again)
# but ``*`` and ``5/2`` expand over 0-6.
_SECOND = ("second", 0, 59, 59, None)
_MINUTE = ("minute", 0, 59, 59, None)
_HOUR = ("hour", 0, 23, 23, None)
_DOM = ("day-of-month", 1, 31, 31, None)
_MONTH = ("month", 1, 12, 12, _MONTH_NAMES)
_DOW = ("day-of-week", 0, 7, 6, _DOW_NAMES)
_YEAR = ("year", 1970, _YEAR_HORIZON, _YEAR_HORIZON, None)

_FieldSpec = Tuple[str, int, int, int, Optional[Mapping[str, int]]]

#: field layouts by column count, mirroring ``CronTab.__init__``'s slicing
_LAYOUTS: Mapping[int, Tuple[_FieldSpec, ...]] = {
    5: (_MINUTE, _HOUR, _DOM, _MONTH, _DOW),
    6: (_MINUTE, _HOUR, _DOM, _MONTH, _DOW, _YEAR),
    7: (_SECOND, _MINUTE, _HOUR, _DOM, _MONTH, _DOW, _YEAR),
}


def _hash_value(hash_key: str, label: str) -> int:
    """The stable integer a hashed item draws its value from.

    sha256 rather than ``hash()``: the slot must be identical across
    processes, restarts and hosts (PYTHONHASHSEED randomizes ``hash()``),
    exactly like the job-set fingerprint (:mod:`cronstable.fingerprint`).
    Salted with the field label so ``H H * * *`` picks an uncorrelated
    minute and hour instead of the same residue twice.
    """
    digest = hashlib.sha256(
        "{}\n{}".format(label, hash_key).encode("utf-8")
    ).digest()
    return int.from_bytes(digest[:8], "big")


def _expand_hash_item(
    item: str, low: str, spec: _FieldSpec, hash_key: Optional[str]
) -> str:
    """One ``H`` item, expanded to the explicit values it hashes to.

    Returns a comma-joined numeric list (``"7,22,37,52"`` for a minute
    ``H/15``), which the ordinary item parser then treats like any other
    values, so ``H`` needs no cases in the matching or search code.
    """
    label, lo, hi, step_end, _names = spec
    if label == "year":
        raise ValueError(
            "'H' is not supported in the year field (a hashed year would "
            "pin the schedule to one arbitrary year)"
        )
    match = _HASH_ITEM.match(low)
    if match is None:
        raise ValueError(
            "invalid {} field {!r}: an 'H' item takes the forms H, H/n, "
            "H(a-b) or H(a-b)/n (numeric range only)".format(label, item)
        )
    if hash_key is None:
        raise ValueError(
            "'H' in the {} field needs a hash key (the job name), which "
            "this context does not supply".format(label)
        )
    a_text, b_text, step_text = match.groups()
    if a_text is not None:
        start, end = int(a_text, 10), int(b_text, 10)
        for value in (start, end):
            if not lo <= value <= hi:
                raise ValueError(
                    "{} value {} out of range [{}, {}]".format(
                        label, value, lo, hi
                    )
                )
        if start > end:
            raise ValueError(
                "{} range start {} > end {}".format(label, start, end)
            )
    else:
        start, end = lo, step_end
        if spec is _DOM:
            end = _HASH_DOM_END  # rangeless H, bare or H/n: never land
            # on a day short months lack; H(1-31) opts back in
    span = end - start + 1
    value = _hash_value(hash_key, label)
    if step_text is None:
        return str(start + value % span)
    step = int(step_text, 10)
    if step <= 0:
        raise ValueError(
            "{} step must be positive, got {}".format(label, step)
        )
    if step > span:
        raise ValueError(
            "{} step {} exceeds the H range's span of {} (the hashed "
            "offset could fall past the range's end)".format(label, step, span)
        )
    values = range(start + value % step, end + 1, step)
    return ",".join(str(v) for v in values)


def _expand_hash_field(
    text: str, spec: _FieldSpec, hash_key: Optional[str]
) -> str:
    """Replace every ``H`` item of one field with its hashed values.

    Case and non-``H`` items pass through byte-identical, so an expression
    without ``H`` is untouched (and the golden-vector compatibility suite
    keeps proving the engine unchanged for the whole legacy dialect).
    """
    items = text.split(",")
    out: List[str] = []
    changed = False
    for item in items:
        low = item.lower()
        if low.startswith("h"):
            out.append(_expand_hash_item(item, low, spec, hash_key))
            changed = True
        else:
            out.append(item)
    return ",".join(out) if changed else text


def _resolve(token: str, spec: _FieldSpec, item: str) -> int:
    """One value token -> int, via the field's name table or base 10."""
    label, lo, hi, _end, names = spec
    if names is not None and token in names:
        value = names[token]
    else:
        try:
            value = int(token, 10)
        except ValueError:
            raise ValueError(
                "invalid {} field {!r}".format(label, item)
            ) from None
    if not lo <= value <= hi:
        raise ValueError(
            "{} value {} out of range [{}, {}]".format(label, value, lo, hi)
        )
    return value


def _parse_item(item: str, spec: _FieldSpec) -> Iterator[int]:
    """Expand one comma-separated item (``*``, ``a``, ``a-b``, with ``/n``).

    Mirrors the old library's validation exactly: a step must be positive,
    no larger than the field's ``hi``, and ``start + step`` must land back
    inside the field's range (so ``*/12`` in the 1-12 month field or
    ``50-59/15`` in the minute field are rejected); a reversed range is an
    error, except that a day-of-week range ending in 0 wraps to 7.
    """
    label, lo, hi, step_end, _names = spec
    head, slash, step_text = item.partition("/")
    step = 1
    if slash:
        if "/" in step_text:
            raise ValueError(
                "invalid {} field {!r}: more than one '/'".format(label, item)
            )
        try:
            step = int(step_text, 10)
        except ValueError:
            raise ValueError(
                "invalid {} step {!r}".format(label, item)
            ) from None
        if step <= 0:
            raise ValueError(
                "{} step must be positive, got {}".format(label, step)
            )
        if step > hi:
            raise ValueError(
                "{} step {} too large (max {})".format(label, step, hi)
            )
    if head == "*":
        start, end = lo, step_end
    elif "-" in head:
        a, _, b = head.partition("-")
        start = _resolve(a, spec, item)
        end = _resolve(b, spec, item)
        if end == 0 and spec is _DOW:
            # A day-of-week range ending in 0 reads its end as Sunday-as-7,
            # UNCONDITIONALLY: 6-0/sat-sun is Sat+Sun, and the degenerate
            # 0-0/sun-sun becomes 0-7, every day (a preserved quirk).
            end = 7
        if start > end:
            raise ValueError(
                "{} range start {} > end {}".format(label, start, end)
            )
    else:
        start = _resolve(head, spec, item)
        if not slash:
            yield start
            return
        end = step_end
        if start > end:
            raise ValueError(
                "{} range start {} > end {}".format(label, start, end)
            )
    if slash and not lo <= start + step <= hi:
        raise ValueError(
            "{} step {} from {} escapes [{}, {}]".format(
                label, step, start, lo, hi
            )
        )
    yield from range(start, end + 1, step)


def _parse_plain(text: str, spec: _FieldSpec) -> FrozenSet[int]:
    """A field with no ``L`` forms (second/minute/hour/month/year)."""
    values: Set[int] = set()
    for item in text.split(","):
        if item.startswith("l"):
            raise ValueError(
                "'L' is only valid in the day-of-month and day-of-week "
                "fields, not {}".format(spec[0])
            )
        values.update(_parse_item(item, spec))
    return frozenset(values)


def _parse_dom(text: str) -> Tuple[FrozenSet[int], bool]:
    """Day-of-month: plain values plus an optional bare ``L`` (last day)."""
    values: Set[int] = set()
    last = False
    for item in text.split(","):
        if item == "l":
            last = True
        elif item.startswith("l"):
            raise ValueError(
                "'L' in the day-of-month field must stand alone "
                "(got {!r})".format(item)
            )
        else:
            values.update(_parse_item(item, _DOM))
    return frozenset(values), last


def _parse_dow(text: str) -> Tuple[FrozenSet[int], FrozenSet[int]]:
    """Day-of-week: plain values plus ``L``-prefixed last-weekday items.

    Both sets are normalized so 7 (Sunday) is stored as 0; matching then
    never needs the 0/7 equivalence.
    """
    values: Set[int] = set()
    last: Set[int] = set()
    for item in text.split(","):
        if item == "l":
            raise ValueError(
                "a bare 'L' is only valid in the day-of-month field; in "
                "day-of-week write L<n> (e.g. L5 = last Friday)"
            )
        if item.startswith("l"):
            # L<n> or L<a>-<b>, strictly numeric (no names, steps or `*`),
            # each value 0..7.  Unlike a plain range, a reversed L-range is
            # NOT an error -- it is legal and matches nothing -- and an end
            # of 0 stays 0 (no Sunday-as-7 wrap).  Preserved quirks.
            a, dash, b = item[1:].partition("-")
            if not a.isdigit() or (dash and not b.isdigit()):
                raise ValueError(
                    "an L day-of-week item takes a day number or numeric "
                    "range 0..7, got {!r}".format(item)
                )
            lo = int(a, 10)
            hi = int(b, 10) if dash else lo
            for value in (lo, hi):
                if not 0 <= value <= 7:
                    raise ValueError(
                        "day-of-week value {} out of range [0, 7]".format(
                            value
                        )
                    )
            last.update(range(lo, hi + 1))
        else:
            values.update(_parse_item(item, _DOW))
    return (
        frozenset(v % 7 for v in values),
        frozenset(v % 7 for v in last),
    )


class CronTab:
    """One parsed cron expression; see the module docstring for the dialect.

    Equality is semantic -- two expressions that fire on the identical set
    of instants compare equal (``*/5 * * * *`` == ``0-59/5 * * * *``,
    ``@daily`` == ``0 0 * * *``) -- because the scheduler's reload path uses
    ``==`` to keep an unchanged job's next-fire instant (see
    ``Cron._same_schedule``).  Instances are deliberately unhashable, like
    the class this replaced.  ``str()`` is the whitespace-normalized source
    expression, giving the dag scheduler's schedule signature a stable value
    across reloads.
    """

    __slots__ = (
        "_source",
        "_resolved",
        "_seconds",
        "_minutes",
        "_hours",
        "_dom",
        "_dom_last",
        "_months",
        "_dow",
        "_dow_last",
        "_years",
        "_hours_sorted",
        "_minutes_sorted",
        "_seconds_sorted",
        "_months_sorted",
        "_years_sorted",
    )

    def __init__(self, crontab: str, hash_key: Optional[str] = None) -> None:
        self._source = " ".join(crontab.split())
        self._resolved = self._source
        fields = crontab.lower().split()
        display: Optional[List[str]] = self._source.split()
        if len(fields) == 1 and fields[0] in _MACROS:
            self._source = fields[0]
            self._resolved = fields[0]
            fields = _MACROS[fields[0]].split()
            display = None  # macros carry no H item to resolve
        if not 5 <= len(fields) <= 7:
            raise ValueError(
                "expected 5 to 7 whitespace-separated cron fields "
                "(or a supported @-nickname), got {}".format(len(fields))
            )
        # kept for the dialect hint below: the columns as the user wrote
        # them, before the second/year columns are sliced away.
        raw_fields = tuple(fields)
        if display is not None:
            # Expand every H item to the explicit values it hashes to,
            # BEFORE the ordinary field parse: the substituted text is
            # plain dialect, so matching and search need no hash cases.
            # Expansion runs over the original-case tokens and non-H items
            # pass through byte-identical, keeping ``resolved_source``
            # faithful to how the user spelled the rest of the field.
            try:
                expanded = [
                    _expand_hash_field(text, spec, hash_key)
                    for text, spec in zip(
                        display, _LAYOUTS[len(fields)], strict=True
                    )
                ]
            except ValueError as err:
                hint = _quartz_hint(raw_fields)
                if hint is not None:
                    raise ValueError("{} ({})".format(err, hint)) from None
                raise
            self._resolved = " ".join(expanded)
            fields = [text.lower() for text in expanded]
        # 5 fields: implicit second 0, any year.  6 fields: a trailing year
        # column.  7 fields: a leading second column as well.
        if len(fields) == 7:
            second_text = fields[0]
            fields = fields[1:]
        else:
            second_text = "0"
        if len(fields) == 6:
            year_text: Optional[str] = fields[5]
            if year_text == "*":
                year_text = None  # matches like an absent column
        else:
            year_text = None
        # Quartz compatibility: '?' standing alone in a day field is that
        # dialect's "unrestricted", read here as '*'.  Only the day fields:
        # a '?' anywhere else keeps failing (with a hint), which is what
        # turns a mis-pasted seconds-first Quartz layout into a clear error
        # instead of a silently shifted schedule.
        dom_text = "*" if fields[2] == "?" else fields[2]
        dow_text = "*" if fields[4] == "?" else fields[4]
        try:
            self._seconds = _parse_plain(second_text, _SECOND)
            self._minutes = _parse_plain(fields[0], _MINUTE)
            self._hours = _parse_plain(fields[1], _HOUR)
            self._dom, self._dom_last = _parse_dom(dom_text)
            self._months = _parse_plain(fields[3], _MONTH)
            self._dow, self._dow_last = _parse_dow(dow_text)
            self._years: Optional[FrozenSet[int]] = (
                _parse_plain(year_text, _YEAR)
                if year_text is not None
                else None
            )
        except ValueError as err:
            hint = _quartz_hint(raw_fields)
            if hint is not None:
                raise ValueError("{} ({})".format(err, hint)) from None
            raise
        self._seconds_sorted = tuple(sorted(self._seconds))
        self._minutes_sorted = tuple(sorted(self._minutes))
        self._hours_sorted = tuple(sorted(self._hours))
        self._months_sorted = tuple(sorted(self._months))
        self._years_sorted = (
            tuple(sorted(self._years)) if self._years is not None else None
        )

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------
    def __str__(self) -> str:
        return self._source

    def __repr__(self) -> str:
        return "CronTab({!r})".format(self._source)

    @property
    def resolved_source(self) -> str:
        """The source with every ``H`` item replaced by its hashed values.

        Equal to ``str(self)`` for an expression without ``H``.  Always
        plain dialect (a bare value or a comma list per expanded item), so
        it re-parses without a hash key; the dashboards' client-side
        engines and the fire previews run on this text while displaying
        the ``H`` original.
        """
        return self._resolved

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, CronTab):
            return False
        return (
            self._seconds == other._seconds
            and self._minutes == other._minutes
            and self._hours == other._hours
            and self._dom == other._dom
            and self._dom_last == other._dom_last
            and self._months == other._months
            and self._dow == other._dow
            and self._dow_last == other._dow_last
            and self._years == other._years
        )

    # __eq__ without __hash__ makes instances unhashable, matching the old
    # class; nothing in cronstable keys on a CronTab.

    # ------------------------------------------------------------------
    # Parsed field sets
    # ------------------------------------------------------------------
    # Ground truth for the tooling around the engine (the linter, the
    # describers, the preview endpoint), which would otherwise have to
    # re-parse the expression text and could drift from what actually
    # matches.  Every value is immutable and already normalized.

    @property
    def seconds(self) -> FrozenSet[int]:
        """Matching seconds, 0-59 (``{0}`` unless a 7-field form set them)."""
        return self._seconds

    @property
    def minutes(self) -> FrozenSet[int]:
        """Matching minutes, 0-59."""
        return self._minutes

    @property
    def hours(self) -> FrozenSet[int]:
        """Matching hours, 0-23."""
        return self._hours

    @property
    def days_of_month(self) -> FrozenSet[int]:
        """Explicit day-of-month values, 1-31 (a bare ``L`` is separate)."""
        return self._dom

    @property
    def last_day_of_month(self) -> bool:
        """Whether a bare ``L`` also matches each month's final day."""
        return self._dom_last

    @property
    def months(self) -> FrozenSet[int]:
        """Matching months, 1-12."""
        return self._months

    @property
    def days_of_week(self) -> FrozenSet[int]:
        """Matching weekdays, 0-6 with Sunday as 0 (7 already folded)."""
        return self._dow

    @property
    def last_days_of_week(self) -> FrozenSet[int]:
        """Weekdays matched only as the month's LAST such day (``L<n>``)."""
        return self._dow_last

    @property
    def years(self) -> Optional[FrozenSet[int]]:
        """Explicit years, or ``None`` when the column is ``*`` or absent."""
        return self._years

    # ------------------------------------------------------------------
    # Matching
    # ------------------------------------------------------------------
    def test(self, entry: datetime.datetime) -> bool:
        """Whether ``entry``'s civil fields match (microseconds ignored)."""
        return (
            entry.second in self._seconds
            and entry.minute in self._minutes
            and entry.hour in self._hours
            and entry.month in self._months
            and (self._years is None or entry.year in self._years)
            and self._day_matches(entry.year, entry.month, entry.day)
        )

    def _day_matches(self, year: int, month: int, day: int) -> bool:
        """The AND of the day-of-month and day-of-week constraints."""
        month_end = calendar.monthrange(year, month)[1]
        if day not in self._dom and not (self._dom_last and day == month_end):
            return False
        # Python weekday(): Mon=0..Sun=6 -> cron: Sun=0..Sat=6.
        dow = (datetime.date(year, month, day).weekday() + 1) % 7
        if dow in self._dow:
            return True
        return (
            dow in self._dow_last
            and day > month_end - 7  # the month's last such weekday
        )

    # ------------------------------------------------------------------
    # Next occurrence
    # ------------------------------------------------------------------
    def next(
        self,
        now: Optional[datetime.datetime] = None,
        default_utc: bool = False,
    ) -> Optional[float]:
        """Seconds until the next occurrence STRICTLY after ``now``.

        ``None`` when the schedule never occurs again (a fixed past year, or
        a date that never exists) -- the search stops at year 2099.  For an
        aware ``now`` the result is true elapsed seconds: the matching civil
        instant is resolved in ``now``'s zone (``fold=0``), so a DST change
        inside the interval is accounted for.  ``default_utc`` only matters
        when ``now`` is omitted: it picks the UTC instead of the local wall
        clock, exactly like the library this replaced.
        """
        if now is None:
            if default_utc:
                now = datetime.datetime.now(datetime.timezone.utc).replace(
                    tzinfo=None
                )
            else:
                now = datetime.datetime.now()
        civil = now.replace(tzinfo=None)
        if now.tzinfo is None:
            target = self._next_civil(civil)
            if target is None:
                return None
            return (target - civil).total_seconds()
        # Aware: the delay to the next REAL instant, i.e. the first
        # :meth:`occurrences` yield after ``now``.  Each civil match is
        # resolved in the zone (fold=0) and compared through UTC, so a
        # match the spring-forward gap swallows counts once at its shifted
        # label, and a wall time ``now`` has already passed on the first
        # leg of a fall-back hour is not offered again on the second leg
        # (comparisons between datetimes sharing a tzinfo ignore ``fold``,
        # which is why the civil answer alone can come out negative).
        now_utc = now.astimezone(datetime.timezone.utc)
        while True:
            target = self._next_civil(civil)
            if target is None:
                return None
            resolved_utc = target.replace(tzinfo=now.tzinfo).astimezone(
                datetime.timezone.utc
            )
            if resolved_utc > now_utc:
                return (resolved_utc - now_utc).total_seconds()
            resolved_civil = resolved_utc.astimezone(now.tzinfo).replace(
                tzinfo=None
            )
            civil = max(target, resolved_civil)

    def _next_civil(
        self, civil: datetime.datetime
    ) -> Optional[datetime.datetime]:
        """Smallest whole-second civil instant strictly after ``civil``."""
        base = civil.replace(microsecond=0) + datetime.timedelta(seconds=1)
        year, month, day = base.year, base.month, base.day
        tod: Optional[datetime.time] = base.time()
        while year <= _YEAR_HORIZON:
            years_sorted = self._years_sorted
            if years_sorted is not None and year not in years_sorted:
                next_year = self._next_in(years_sorted, year)
                if next_year is None:
                    return None
                year, month, day, tod = next_year, 1, 1, None
                continue
            if month not in self._months:
                nxt = self._next_in(self._months_sorted, month)
                if nxt is None:
                    year, month = year + 1, self._months_sorted[0]
                else:
                    month = nxt
                day, tod = 1, None
                continue
            month_end = calendar.monthrange(year, month)[1]
            while day <= month_end:
                if self._day_matches(year, month, day):
                    t = self._first_time(tod)
                    if t is not None:
                        return datetime.datetime.combine(
                            datetime.date(year, month, day), t
                        )
                day += 1
                tod = None
            month += 1
            day, tod = 1, None
            if month > 12:
                year, month = year + 1, 1
        return None

    @staticmethod
    def _next_in(ordered: Tuple[int, ...], current: int) -> Optional[int]:
        """First element of ``ordered`` greater than ``current``."""
        for value in ordered:
            if value > current:
                return value
        return None

    def _first_time(
        self, at_or_after: Optional[datetime.time]
    ) -> Optional[datetime.time]:
        """Earliest matching time of day, at/after ``at_or_after`` if set."""
        if at_or_after is None:
            return datetime.time(
                self._hours_sorted[0],
                self._minutes_sorted[0],
                self._seconds_sorted[0],
            )
        for hour in self._hours_sorted:
            if hour < at_or_after.hour:
                continue
            if hour > at_or_after.hour:
                return datetime.time(
                    hour, self._minutes_sorted[0], self._seconds_sorted[0]
                )
            for minute in self._minutes_sorted:
                if minute < at_or_after.minute:
                    continue
                if minute > at_or_after.minute:
                    return datetime.time(hour, minute, self._seconds_sorted[0])
                for second in self._seconds_sorted:
                    if second >= at_or_after.second:
                        return datetime.time(hour, minute, second)
        return None

    # ------------------------------------------------------------------
    # Previous occurrence
    # ------------------------------------------------------------------
    def prev(
        self,
        now: Optional[datetime.datetime] = None,
        default_utc: bool = False,
    ) -> Optional[float]:
        """Seconds since the most recent occurrence STRICTLY before ``now``.

        The mirror of :meth:`next`: ``None`` when the schedule has no
        occurrence at or after 1970 (the year column's floor).  For an
        aware ``now`` the result is true elapsed seconds since the most
        recent REAL instant, under the same DST policy as
        :meth:`occurrences`: a match the spring-forward gap swallows
        counts once at its shifted label, and a fall-back wall time counts
        on its first leg only.  Callers use this to answer "when should
        the last run have been?" (missed-run and late-run detection)
        without replaying the schedule forward themselves.
        """
        if now is None:
            if default_utc:
                now = datetime.datetime.now(datetime.timezone.utc).replace(
                    tzinfo=None
                )
            else:
                now = datetime.datetime.now()
        civil = now.replace(tzinfo=None)
        if now.tzinfo is None:
            target = self._prev_civil(civil)
            if target is None:
                return None
            return (civil - target).total_seconds()
        # Aware: seconds since the last REAL instant, i.e. the final
        # :meth:`occurrences` yield strictly before ``now``.  A backward
        # civil scan alone goes wrong at DST edges: a match inside the
        # spring-forward gap resolves FORWARD, possibly past ``now``, and
        # when ``now`` sits on the second leg of a fall-back hour the most
        # recent fire lives at a LATER civil label than ``now``'s.  So
        # walk back to a match whose label the zone leaves in place, then
        # replay the forward iterator (the fire policy itself) from there
        # and keep the last instant before ``now``.
        tz = now.tzinfo
        utc = datetime.timezone.utc
        now_utc = now.astimezone(utc)
        anchor = self._prev_civil(civil)
        while anchor is not None:
            resolved = anchor.replace(tzinfo=tz).astimezone(utc).astimezone(tz)
            if resolved.replace(tzinfo=None) == anchor:
                last: Optional[datetime.datetime] = None
                start = (anchor - datetime.timedelta(seconds=1)).replace(
                    tzinfo=tz
                )
                for instant in self.occurrences(start):
                    instant_utc = instant.astimezone(utc)
                    if instant_utc >= now_utc:
                        break
                    last = instant_utc
                if last is not None:
                    return (now_utc - last).total_seconds()
            anchor = self._prev_civil(anchor)
        return None

    def _prev_civil(
        self, civil: datetime.datetime
    ) -> Optional[datetime.datetime]:
        """Largest whole-second civil instant strictly before ``civil``."""
        if civil.microsecond:
            base = civil.replace(microsecond=0)
        else:
            base = civil - datetime.timedelta(seconds=1)
        year, month, day = base.year, base.month, base.day
        tod: Optional[datetime.time] = base.time()
        while year >= _YEAR_FLOOR:
            years_sorted = self._years_sorted
            if years_sorted is not None and year not in years_sorted:
                prev_year = self._prev_in(years_sorted, year)
                if prev_year is None:
                    return None
                year, month, day, tod = prev_year, 12, 31, None
                continue
            if month not in self._months:
                prv = self._prev_in(self._months_sorted, month)
                if prv is None:
                    year, month = year - 1, self._months_sorted[-1]
                else:
                    month = prv
                day, tod = 31, None
                continue
            month_end = calendar.monthrange(year, month)[1]
            if day > month_end:
                day = month_end  # clamp the rollback sentinel into the month
            while day >= 1:
                if self._day_matches(year, month, day):
                    t = self._last_time(tod)
                    if t is not None:
                        return datetime.datetime.combine(
                            datetime.date(year, month, day), t
                        )
                day -= 1
                tod = None
            month -= 1
            day, tod = 31, None
            if month < 1:
                year, month = year - 1, 12
        return None

    @staticmethod
    def _prev_in(ordered: Tuple[int, ...], current: int) -> Optional[int]:
        """Last element of ``ordered`` less than ``current``."""
        for value in reversed(ordered):
            if value < current:
                return value
        return None

    def _last_time(
        self, at_or_before: Optional[datetime.time]
    ) -> Optional[datetime.time]:
        """Latest matching time of day, at/before ``at_or_before`` if set."""
        if at_or_before is None:
            return datetime.time(
                self._hours_sorted[-1],
                self._minutes_sorted[-1],
                self._seconds_sorted[-1],
            )
        for hour in reversed(self._hours_sorted):
            if hour > at_or_before.hour:
                continue
            if hour < at_or_before.hour:
                return datetime.time(
                    hour, self._minutes_sorted[-1], self._seconds_sorted[-1]
                )
            for minute in reversed(self._minutes_sorted):
                if minute > at_or_before.minute:
                    continue
                if minute < at_or_before.minute:
                    return datetime.time(
                        hour, minute, self._seconds_sorted[-1]
                    )
                for second in reversed(self._seconds_sorted):
                    if second <= at_or_before.second:
                        return datetime.time(hour, minute, second)
        return None

    # ------------------------------------------------------------------
    # Occurrence iteration
    # ------------------------------------------------------------------
    def occurrences(
        self,
        start: Optional[datetime.datetime] = None,
        default_utc: bool = False,
    ) -> Iterator[datetime.datetime]:
        """Yield successive fire instants strictly after ``start``.

        Exactly the instants the scheduler would fire, in order, ending
        when the schedule has no further occurrence (the 2099 horizon).
        With an aware ``start`` every yield is an aware datetime in
        ``start``'s zone and the iteration steps through REAL instants: a
        wall time a spring-forward transition skips is yielded once at its
        shifted label (the clock that actually exists at that instant) and
        a repeated fall-back wall time is yielded on its first occurrence
        only, so one real instant is never yielded twice.  With a naive
        ``start`` the yields are civil wall-clock datetimes.
        ``default_utc`` matters only when ``start`` is omitted, exactly as
        in :meth:`next`.
        """
        if start is None:
            if default_utc:
                start = datetime.datetime.now(datetime.timezone.utc).replace(
                    tzinfo=None
                )
            else:
                start = datetime.datetime.now()
        tz = start.tzinfo
        civil = start.replace(tzinfo=None)
        while True:
            target = self._next_civil(civil)
            if target is None:
                return
            if tz is None:
                yield target
                civil = target
                continue
            # Resolve in the zone (fold=0, next()'s rule), then re-render
            # through UTC: a nonexistent spring-forward wall time comes back
            # as the label the wall clock actually shows at that instant,
            # and continuing the civil search from the rendered label steps
            # past both the skipped hour and a fall-back repeat.
            resolved = (
                target.replace(tzinfo=tz)
                .astimezone(datetime.timezone.utc)
                .astimezone(tz)
            )
            yield resolved
            civil = resolved.replace(tzinfo=None)
